#!/usr/bin/env node
// Builds the browser-side editor (src/client/editor.js) into an embeddable module
// at src/client/editor.bundle.js exporting EDITOR_JS as a string. That string is
// inlined into the spec page by src/index.js, so it travels inside the single
// bundled cli.cjs / SEA binary and works offline. Committed to the repo so plain
// `node src/index.js` dev runs need no pre-build.
//
// Usage: npm run build:client

import { build } from "esbuild";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const ENTRY = path.join(ROOT, "src/client/editor.js");
const OUT = path.join(ROOT, "src/client/editor.bundle.js");

const result = await build({
  entryPoints: [ENTRY],
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2020",
  minify: true,
  write: false,
});

const js = result.outputFiles[0].text;
const module = `// AUTO-GENERATED by scripts/build-client.js — do not edit by hand.
// Browser editor bundle, inlined into the spec page. Run \`npm run build:client\` to regenerate.
export const EDITOR_JS = ${JSON.stringify(js)};
`;

fs.writeFileSync(OUT, module);
const kb = (Buffer.byteLength(js) / 1024).toFixed(0);
console.log(`  ✓ src/client/editor.bundle.js  (${kb} KB browser bundle)`);
